version: '3'

volumes:
  django_with_react_local_postgres_data: {}
  django_with_react_local_postgres_data_backups: {}

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    restart: always
    depends_on:
      - django

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_with_react_local_django
    container_name: django_with_react_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django_with_react_production_postgres
    container_name: django_with_react_local_postgres
    volumes:
      - django_with_react_local_postgres_data:/var/lib/postgresql/data:Z
      - django_with_react_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: django_with_react_local_docs
    container_name: django_with_react_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_with_react:/app/django_with_react:z
    ports:
      - "7000:7000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: django_with_react_local_redis

  celeryworker:
    <<: *django
    image: django_with_react_local_celeryworker
    container_name: django_with_react_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: django_with_react_local_celerybeat
    container_name: django_with_react_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: django_with_react_local_flower
    container_name: django_with_react_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
